name: workflow practice

on: 
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop 

jobs:
  linting_job:
    runs-on: ubuntu-latest

    steps:
     - name: message displaying
       run: echo "builded first pipeline"

     - name: coping to branch
       uses: actions/checkout@v4 
     
     - name: displaying details 
       run: |
         echo "the name of the event ${{github.event_name}}"
         git reflog
     - name: installing Html linting_job
       run: npm install --save-dev htmlhint
     - name: running npx
       run: npx htmlhint "**/*.html"
       
       
