name: Create Pull Request Automatically

on:
  push:
    branches:
      - '**'  # Trigger on pushes to any branch



jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Use the GITHUB_TOKEN to authenticate
        base: main  # The branch you want to merge into (main)
        head: ${{ github.ref_name }}  # The branch that was just pushed
        title: "Automated PR: Merge ${{ github.ref_name }} into main"
        body: "This is an automated pull request created by GitHub Actions."
